version: "3"
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-bedrock-server
    restart: always
    environment:
      # Enable SSH
      ENABLE_SSH: true
      # Server settings
      EULA: "TRUE"
      GAMEMODE: survival
      SERVER_NAME: Moaicraft
      LEVEL_NAME: Moaiworld
      LEVEL_SEED: -2746961253358476370
      DIFFICULTY: normal
      ALLOW_CHEATS: true
      ALLOW_LIST: true
      CLIENT_SIDE_CHUNK_GENERATION_ENABLED: true
    # Expose the mc-server-runner's SSH port to just the backup container
    expose:
      - 2222
    ports:
      - 19132:19132/udp
    volumes:
      - ./minecraft:/data
    stdin_open: true
    tty: true

  backup:
    container_name: backup
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      # Make sure the minecraft service starts before the backup
      minecraft:
        condition: service_healthy
    volumes:
      # Map your backups folder into /backups
      - ./backups:/backups
      # Map the data folders for the server
      - ./minecraft:/minecraft
      # (Optional) Map a configuration folder separately from the backups.
      - ./backup-config:/config

  websocket:
    container_name: websocket
    image: joanroig/admincraft-websocket:latest
    restart: always
    depends_on:
      # Make sure the minecraft service starts before the websockets service
      minecraft:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - ./certs/server.crt:/usr/src/app/certs/server.crt:ro # Needed if environment.USE_SSL is "true"
      - ./certs/server.key:/usr/src/app/certs/server.key:ro # Needed if environment.USE_SSL is "true"
    environment:
      SECRET_KEY: YOUR_SECRET_KEY_HERE
      USE_SSL: "true" # Change to "false" to disable SSL
